[package]
name = "homeassistant-rest-rs"
version = "0.1.0"
edition = "2021"
description = "Homeassistant REST API client"
readme = "README.md"
repository = "https://github.com/StefanBossbaly/homeassistant-rest-rs/"
authors = ["Stefan Bossbaly <sbossb@gmail.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
reqwest = { version = "0.11.14", features = ["json"] }
serde = "1.0.157"
serde_derive = "1.0.157"
serde_json = "1.0.94"
url = "2.3.1"
