[package]
name = "home-assistant-rest"
version = "0.2.0"
edition = "2021"
description = "Home Assistant Async REST API Client"
readme = "README.md"
repository = "https://github.com/StefanBossbaly/home-assistant-rest/"
authors = ["Stefan Bossbaly <sbossb@gmail.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.33", features = ["serde"] }
reqwest = { version = "0.11.23", features = ["json"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.112"
url = "2.5.0"
serde_qs = "0.12.0"
log = "0.4.20"
bytes = "1.5.0"

[dev-dependencies]
mockito = "1.2.0"
tokio = { version = "1.35.1", features = ["full"] }
